apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helloworld-helm
  namespace: feng-flux-helm
spec:
  interval: 5m
  chart:
    spec:
      chart: helloworld-helm
      version: '0.2.0'
      sourceRef:
        kind: HelmRepository
        name: app-sample
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1

