apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nested-helloworld-app
  namespace: nested-helloworld-app
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nested-helloworld-app
